

_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    # Set filtered_alias_mode to 'disallow' to forbid more than 2 filtered aliases per index
    # Set filtered_alias_mode to 'warn' to allow more than 2 filtered aliases per index but warns about it (default)
    # Set filtered_alias_mode to 'nowarn' to allow more than 2 filtered aliases per index silently
    #filtered_alias_mode: warn
    #do_not_fail_on_forbidden: false
    #kibana:
    # Kibana multitenancy
    #multitenancy_enabled: true
    #server_username: kibanaserver
    #index: '.kibana'
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: true
        #internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
        internalProxies: '.*' # trust all internal proxies, regex pattern
        remoteIpHeader:  'x-forwarded-for'
        ###### see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html for regex help
        ###### more information about XFF https://en.wikipedia.org/wiki/X-Forwarded-For
        ###### and here https://tools.ietf.org/html/rfc7239
        ###### and https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
#      openid_auth_domain:
#        http_enabled: true
#        transport_enabled: true
#        order: 1
#        http_authenticator:
#          type: openid
#          challenge: false
#          config:
#            subject_key: preferred_username
#            roles_key: roles
#            openid_connect_url: https://ip-10-0-1-45/auth/realms/poc/.well-known/openid-configuration
#            openid_connect_idp.enable_ssl: true
#            openid_connect_idp.pemtrustedcas_filepath: /usr/share/elasticsearch/config/ssl-cert-snakeoil.pem
#            openid_connect_idp.verify_hostnames: false
#        authentication_backend:
#          type: noop
      
      # proxy_auth_domain:
      #   http_enabled: true
      #   transport_enabled: true
      #   order: 0
      #   http_authenticator:
      #     type: proxy
      #     challenge: false
      #     config:
      #       user_header: "x-proxy-user"
      #       roles_header: "x-proxy-roles"
      #       skip_users:
      #         - "kibanaserver"
      #         - "kibana"
      #         - "apm_system"
      #         - "logstash_system"
      #         - "beats_system"
      #         - "remote_monitoring_user"
      #         - "elastic"
      #   authentication_backend:
      #     type: noop
