spring:
    datasource:
        url: jdbc:mysql://localhost:53306/minor?characterEncoding=UTF-8&serverTimezone=UTC
        username: user1
        password: password
    jpa:
        show-sql: true
        hibernate:
          ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
    flyway:
        enabled: true
        baseline-on-migrate: true
logging:
    level:
        org.springframework.security: debug
        org.hibernate.sql: debug
        org.hibernate.type: debug
        org.hibernate.type.descriptor.sql.BasicBinder: debug
        org.springframework.http: trace
        org.springframework.web: trace

#server:
#    error:
#        include-stacktrace: never
#        include-exception: false
