version: "3.1"
services:
  db:
    image: library/mysql:8.0
    container_name: minor-db-node
    restart: always
    ports:
      - 53306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minor
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command: ["mysqld",
              "--character-set-server=utf8mb4",
              "--collation-server=utf8mb4_general_ci"]
  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080