version: '3.3'
services:
  search-server:
    build: ./src
    container_name: search-server
    restart: always
    ports:
      - 3000:3000
      - 8888:8888
      - 8000:8000
    volumes:
      - ./src/:/app/code/
    tty: true
    stdin_open: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - minor-service-net
    expose:
      - "8000"
networks:
  minor-service-net:
    external: true
