version: "3.1"
services:
  minor-db-node:
    image: library/mysql:8.0
    container_name: minor-db-node
    restart: always
    ports:
      - 3306:53306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minor
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    command: [ "mysqld",
               "--character-set-server=utf8mb4",
               "--collation-server=utf8mb4_general_ci" ]
    networks:
      - minor-service-net
  spring:
    build:
      dockerfile: spring-dockerfile
    restart: always
    ports:
      - 8080:8080
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://minor-db-node:3306/minor?characterEncoding=UTF-8&serverTimezone=UTC
    depends_on:
      - minor-db-node
    networks:
      - minor-service-net
networks:
  minor-service-net:
    external: true