version: '3.9'
services:
  rec-node:
    build: ./docker
    ports:
      - 5000:5000
    expose:
      - "5000"
    volumes:
      - ./:/app/workspace/rec-crawl/src/
    tty: true
    stdin_open: true
networks:
  default:
